import { readFileSync, readdirSync, statSync, appendFileSync } from "node:fs";
import { join } from "node:path";

import { summarize } from "./summarize.js";
import { toMarkdown } from "./format.js";
import type { FleetReport, ProvenanceDoc } from "./types.js";

export interface RunnerEnv {
  inputs: Record<string, string | undefined>;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  readFile?: (path: string) => string;
  readDir?: (path: string) => string[];
  isFile?: (path: string) => boolean;
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  report: FleetReport;
  commentPosted: boolean;
  reason?: string;
}

function loadDocs(
  dir: string,
  read: (path: string) => string,
  list: (path: string) => string[],
  isFile: (path: string) => boolean
): ProvenanceDoc[] {
  const out: ProvenanceDoc[] = [];
  for (const entry of list(dir)) {
    if (!entry.endsWith(".json")) continue;
    const full = join(dir, entry);
    if (!isFile(full)) continue;
    out.push(JSON.parse(read(full)) as ProvenanceDoc);
  }
  return out;
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const promptsDir = required(env.inputs, "prompts_dir");
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const failOnHigh = (env.inputs.fail_on_high ?? "true").toLowerCase() !== "false";
  const token = env.inputs.github_token ?? "";

  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const list = env.readDir ?? ((p) => readdirSync(p));
  const isFile = env.isFile ?? ((p) => statSync(p).isFile());
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  const docs = loadDocs(promptsDir, read, list, isFile);
  const report = summarize(docs);
  const markdown = toMarkdown(report);

  setOutput(env, "total-prompts", String(report.prompts));
  setOutput(env, "high-findings", String(report.findings.filter((f) => f.severity === "high").length));
  setOutput(env, "approved-count", String(report.byState.approved));
  setOutput(env, "deprecated-count", String(report.byState.deprecated));

  write(`\n${markdown}\n`);

  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `${markdown}\n\n_Generated by [prompt-provenance-fleet-summary-action](https://github.com/mizcausevic-dev/prompt-provenance-fleet-summary-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (failOnHigh && !report.ok) {
    write(`::error::Prompt provenance fleet has ${report.findings.filter((f) => f.severity === "high").length} high-severity finding(s).`);
    return { exitCode: 1, report, commentPosted, reason };
  }

  return { exitCode: 0, report, commentPosted, reason };
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
